require('sets')
require('keys')
require('plugins')
require('colors')

require('lsp')
require('config.cmp')
require('config.treesitter')
require('config.telescope')
require('config.lualine')
require('config.comment')
require('config.ultisnips')
require('config.nvim-tree')
require('config.toggleterm')
require('config.bufferline')
require('config.vimtex')
